config/routes.rb
Rails.application.routes.draw do
  get 'chats/index'
  get 'chats/show'
  devise_for :users
  get 'users/search', to: "users#search"
  resources :chats do
    get "time_show", on: :member
    collection do
      get 'search'
    end
  end
  root to: "chats#index"
  resources :rooms do
    get "time_show", on: :member
    collection do
      get 'search'
    end
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user

  def self.search(search)
    if search != ""
      User.where('nickname LIKE(?)', "%#{search}%")
    else
      User.all
    end
  end

  validates :sentence, presence: true
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def index
    @my_chats=current_user.chats
    @chat_partners=User.where.not(id:current_user.id)
  end

  def show
    @partner=User.find(params[:id])
    @chat_partners=User.where.not(id:current_user.id)
    @chats_by_myself=Chat.where(user_id: current_user.id,partner_id: @partner.id)
    @chats_by_other=Chat.where(user_id: @partner.id,partner_id: current_user.id)
    @chats=@chats_by_myself.or(@chats_by_other)
    @chats=@chats.order(:created_at)

  end

  def time_show
   @day_params = params[:format]
   @partner=User.find(params[:id])
   @chat_partners=User.where.not(id:current_user.id)
   @chats_by_myself=Chat.where(user_id: current_user.id,partner_id: @partner.id)
   @chats_by_other=Chat.where(user_id: @partner.id,partner_id: current_user.id)
   @chats=@chats_by_myself.or(@chats_by_other)
   @chats=@chats.order(:created_at)
  end

  def search
    @chats = Chat.search(params[:keyword])
    @my_chats=current_user.chats
    @chat_partners=User.where.not(id:current_user.id)
  end

  #def destroy
   # current_user.destroy
   # flash[:notice] = 'ユーザーアカウントを削除しました'
   # redirect_to new_user_session_path
 # end

  #def create
    #@chat = Chat.new(post_params)
  #end


end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_chat.html.erb
<div class='message'>
  <p><%= chat.sentence %></p>
</div>

app/views/chats/_users.html.erb
          <%@chat_partners.each do |chat_partner|%>
           <%=link_to "/chats/#{chat_partner.id}" do%>
           <p class="talk-room-one"><i class="fas fa-comments">　</i><%= "#{chat_partner.nickname}" %></p>
           <% end %>
          <%end%>

app/views/chats/index.html.erb
 <div class="box-wrapper">
    <div class="side-bar-index">
    <h2>Chat</h2>

       <%= form_with(url: search_chats_path, local: true, method: :get, class: "search-form") do |form| %>
          <%= form.text_field :keyword, placeholder: "ユーザー検索", class: "input-box" %>
          <button class="search-button">
            <%= image_tag "search.png", class:"search-icon" %>
          </button>
        <% end %>

        <ul class="talk-room">
          <%@chat_partners.each do |chat_partner|%>
           <%=link_to "/chats/#{chat_partner.id}" do%>
           <p class="talk-room-one"><i class="fas fa-comments">　</i><%= "#{chat_partner.nickname}" %></p>
           <% end %>
          <%end%>
        </ul>
    </div>
    <div class="side-bar-index2">
    <h2>Talk Room作成</h2>
        <ul class="side-text-roomenter">
          <li>複数人数のトークはこちらから</li>
           <%=link_to rooms_path do%>
           <li class="roomenter-btn">Talk Roomページへ</li>
           <% end %>
        </ul>
        <ul class="side-login">
          <!--<li><%=link_to("ログインページ","/", class:"side-login-one")%></li>-->
          <li><%=link_to("ログアウト","/users/sign_out",method: :delete,class:"side-login-one" )%></li>
          <li><%=link_to("#{current_user.nickname}を削除", user_registration_path,method: :delete,class:"side-login-one" , data: {confirm: "ユーザーアカウントを削除しますか？"})%></li>
        </ul>
    </div>
 
  <div class="container-index">
    <h2>Chat Line使い方</h2>
     <ul class="index-text">
          <li class="index-help-chat"><span class="index-help">〜チャット機能〜</span><br>
          ユーザーと1対1でチャットができます。<br>
          日別チャットを確認できるチャットカレンダー機能搭載
          <span class="index-help2">←Chatからユーザーを選んでチャットをしてみよう！</span></li>
          
          <li class="index-help-chat2"><span class="index-help">〜トークルーム機能〜</span><br>
          Talk Roomページから新規ルームを作成し<br>グループチャットができます。<br>
          <span class="index-help2">←Talk Roomからチャットをしてみよう！</span></li>
     </ul>
  </div>
</div>

app/views/chats/search.html.erb
 
    <div class="side-bar-search">
    <h2>Search Result</h2>

        <ul class="talk-room-search">
          <%@chat_partners.each do |chat_partner|%>
              <%if  @chats.ids.include?(chat_partner.id) %>
                <%=link_to "/chats/#{chat_partner.id}" do%>
                <li class="talk-room-search-one"><i class="fas fa-comments">　</i><%= "#{chat_partner.nickname}" %></li>
              <% end %>
            <% end %>
          <%end%>
        </ul>
    </div>

app/views/chats/show.html.erb
 <div class="box-wrapper">
    <div class="side-bar-index">
    <h2>Chat</h2>
           <%= form_with(url: search_chats_path, local: true, method: :get, class: "search-form") do |form| %>
          <%= form.text_field :keyword, placeholder: "ユーザー検索", class: "input-box" %>
          <button class="search-button">
            <%= image_tag "search.png", class:"search-icon" %>
          </button>
        <% end %>
        <ul class="talk-room">
          <%@chat_partners.each do |chat_partner|%>
           <%=link_to "/chats/#{chat_partner.id}" do%>
           <p class="talk-room-one"><i class="fas fa-comments">　</i><%= "#{chat_partner.nickname}" %></p>
           <% end %>
          <%end%>
        </ul>
    </div>
    <div class="side-bar-index2-chat">
    <h2>日ごとのチャットを確認</h2>
      <%= month_calendar do |date| %>
        <%= link_to time_show_chat_path(@partner.id,date),class:"date-one" do %>
          
                <div class="calender-hover"><%= date.day %></div>
        <% end %>
      <% end %>


        <ul class="side-login">

          <li><%=link_to("トップページ","/", class:"side-login-one")%></li>
          <li><%=link_to("ログアウト","/users/sign_out",method: :delete,class:"side-login-one" )%></li>
        </ul>
    </div>

    <div class="container-show-title">
    <h2><%="Chat With  #{@partner.nickname}"%></h2>

    <div id="chats">
     <div id="chats-scroll">
      <% @chats.each do |chat|%>
        <%if chat.user_id==current_user.id%>
          <div class="mycomment">
            <p><%=chat.sentence%></p>
          </div>
          <p class="mycomment-time"><%=chat.created_at.month%>/<%=chat.created_at.day%>　<%=chat.created_at.hour%>:<%= chat.created_at.strftime("%M") %><p>
        <%else%>
          <div class="fukidasi">
            <div class="faceicon">
              <%= image_tag("user.png", class:"img" )%>
              <%=chat.created_at.month%>/<%=chat.created_at.day%>　<%=chat.created_at.hour%>:<%= chat.created_at.strftime("%M") %>
            </div>
           
            <div class="chatting">
              <div class="says">
                <p><%=chat.sentence%></p>
              </div>
            </div>
          </div>
        <%end%>
      <%end%>
     </div>
    </div>


    <form id="send-form">
      <input type="text" id="sentence" placeholder="入力" class="text-box">
      <input type="submit" value="&#xf1d8;" id="send" class="far send-box">
      <input id="current_user_id" type="hidden" value= "<%=current_user.id%>">
      <input id="partner_id" type="hidden" value= "<%=@partner.id%>">
      <input id="chat_time" type="hidden" value= "<%=Time.now.hour%>:<%=Time.now.strftime("%M")%>">
    </form>
  </div>
</div>

app/views/chats/show2.html.erb
      <%= month_calendar do |date| %>
        <%= link_to time_show_chat_path(@partner.id,date),class:"date-one" do %>

          <% @chats.each do |chat|%>
 

                <% if chat.created_at.day == date.day %>
                  <% if chat.created_at.day.count > 1 %>
                    <div class="calender-one"><%= date.day %></div>
                  <% else %>
                    <div><%= date.day %></div>
                  <% end %>

               <% end %>


          <% end %>

        <% end %>
      <% end %>


        received: function(data) {
    //画面を開いているのがチャット送信者だった場合
    if (data["isCurrent_user"]==true){
      $('#chats').append(`<div class='mycomment'><p>${data["sentence"]}</p></div>`);
      $("#chats").scrollTop( $("#chats")[0].scrollHeight );
    }
    //画面を開いているのがチャット受信者だった場合
    else{
      $('#chats').append(`<div class='fukidasi'> <div class="faceicon">
      <img src="/assets/images/user.png"></div>
      <div class='chatting'><div class='says'><p>${data["sentence"]}</p>
      </div></div></div>`);
      $("#chats").scrollTop( $("#chats")[0].scrollHeight );
    }
  },


    received: function(data) {
    return $('#messages').append(data['message']);
  },

app/views/chats/time_show.html.erb
<div class="box-wrapper">
    <div class="side-bar-index">
    <h2>Chat</h2>
         <%= form_with(url: search_chats_path, local: true, method: :get, class: "search-form") do |form| %>
          <%= form.text_field :keyword, placeholder: "ユーザー検索", class: "input-box" %>
          <button class="search-button">
            <%= image_tag "search.png", class:"search-icon" %>
          </button>
        <% end %>
        <ul class="talk-room">
          <%@chat_partners.each do |chat_partner|%>
           <%=link_to "/chats/#{chat_partner.id}" do%>
           <p class="talk-room-one"><i class="fas fa-comments">　</i><%= "#{chat_partner.nickname}" %></p>
           <% end %>
          <%end%>
        </ul>
    </div>

    <div class="side-bar-index2-chat">
    <h2><%=Time.parse(@day_params).year%>年<%=Time.parse(@day_params).month%>月<%=Time.parse(@day_params).day%>日のチャット</h2>
      <%= month_calendar do |date| %>
        <%= link_to time_show_chat_path(@partner.id,date),class:"date-one" do %>
          <% if Time.parse(@day_params).day == date.day%>
            <div class="calender-one"><%= date.day %></div>
          <% else %>
            <div class="calender-one-hover"><%= date.day %></div>
          <% end %>
        <% end %>
      <% end %>

        <ul class="side-login">
         <li><%=link_to("全ての日を表示",chat_path(@partner.id), class:"side-login-one")%></li>
          <li><%=link_to("トップページ","/", class:"side-login-one")%></li>
          <li><%=link_to("ログアウト","/users/sign_out",method: :delete,class:"side-login-one" )%></li>
        </ul>
    </div>

    <div class="container-show-title">
    <h2><%="Chat With  #{@partner.nickname}"%></h2>

    <div id="chats">
      <% @chats.each do |chat|%>

      <% if Time.parse(@day_params).day == chat.created_at.day %>
        <%if chat.user_id==current_user.id%>
          <div class="mycomment">
            <p><%=chat.sentence%></p>
          </div>
         <p class="mycomment-time"> <%=chat.created_at.hour%>:<%= chat.created_at.strftime("%M") %><p>
        <%else%>
          <div class="fukidasi">
            <div class="faceicon">
              <%= image_tag("user.png", class:"img" )%>
               <%=chat.created_at.hour%>:<%= chat.created_at.strftime("%M") %>
            </div>
            <div class="chatting">
              <div class="says">
                <p><%=chat.sentence%></p>
              </div>
            </div>
          </div>
        <%end%>
      <% end %>
      

      <%end%>
    </div>

   <% if Time.parse(@day_params).day == Time.now.day%>
    <form id="send-form">
      <input type="text" id="sentence" placeholder="入力" class="text-box">
      <input type="submit" value="&#xf1d8;" id="send" class="far send-box">
      <input id="current_user_id" type="hidden" value= "<%=current_user.id%>">
      <input id="partner_id" type="hidden" value= "<%=@partner.id%>">
      <input id="chat_time" type="hidden" value= "<%=Time.now.hour%>:<%=Time.now.strftime("%M")%>">
    </form>
  <%end %>
  </div>
</div>