config/routes.rb
Rails.application.routes.draw do
  get 'chats/index'
  get 'chats/show'
  devise_for :users
  get 'users/search', to: "users#search"
  resources :chats do
    get "time_show", on: :member
    collection do
      get 'search'
    end
  end
  root to: "chats#index"
  resources :rooms do
    get "time_show", on: :member
    collection do
      get 'search'
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages,dependent: :destroy
  validates :name, presence: true, length: { maximum: 10 }
  belongs_to :user

  def self.search(search)
    if search != ""
      Room.where('name LIKE(?)', "%#{search}%")
    else
      Room.all
    end
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @rooms = Room.all.order(:id)
  end

  def show
    @rooms = Room.all.order(:id)
    @room = Room.find(params[:id])
    @messages = @room.messages
  end

  def new
    @rooms = Room.all.order(:id)
    @room = Room.new
  end

  def create
    @rooms = Room.all.order(:id)
    @room = Room.new(room_params)
    if @room.save
      flash[:notice] = 'トークルーム作成に成功しました'
      redirect_to room_path(@room.id)
    else
      render :new
    end
  end

def destroy
  @room = Room.find(params[:id])
  if current_user.id == @room.user_id
    @room.destroy
    flash[:notice] = 'トークルームを削除しました'
    redirect_to rooms_path
  else
    flash[:notice] = '削除できません'
    redirect_to rooms_path
  end
end

  def search
    @rooms = Room.search(params[:keyword])
    @talk_room = Room.all
  end

  def time_show
    @day_params = params[:format]
    @rooms = Room.all.order(:id)
    @room = Room.find(params[:id])
    @messages = @room.messages
  end

  private

  def room_params
    params.require(:room).permit(:name).merge(user_id: current_user.id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
 <div class="box-wrapper">
    <div class="side-bar-room">
    <h2>Talk Room</h2>
           <%= form_with(url: search_rooms_path, local: true, method: :get, class: "search-form") do |form| %>
          <%= form.text_field :keyword, placeholder: "ルーム検索", class: "input-box" %>
          <button class="search-button">
            <%= image_tag "search.png", class:"search-icon" %>
          </button>
        <% end %>

        <ul class="talk-room">
          <% @rooms.each do |room| %>
           <%=link_to room_path(room) do%>
           <p class="talk-room-one"><i class="fas fa-comments">　</i><%= "#{room.name}" %></p>
           <% end %>
          <%end%>
        </ul>
    </div>
    <div class="side-bar-room2">
    <h2>Chat</h2>
        <ul class="side-text-roomenter">
          <li>1対1のチャットはこちらから</li>
           <%=link_to root_path do%>
           <li class="roomenter-btn">トップページへ</li>
           <% end %>
        </ul>

        <ul class="side-login">
          <!--<li><%=link_to("ログインページ","/", class:"side-login-one")%></li>-->
          <li><%=link_to("ログアウト","/users/sign_out",method: :delete,class:"side-login-one" )%></li>
        </ul>
    </div>
 
  <div class="container-index">
    <h2>Talk Roomの使い方</h2>
     <ul class="index-text">
          <li class="index-help-chat2"><span class="index-help-room">〜トークルーム作成〜</span><br>
          ←トークルームに入室してグループチャットを楽しもう！<br>
          新たなトークルーム作成は下記ボタンから<br>ルーム名を登録し作成しよう<br>
          <%=link_to new_room_path, class:"roommake-btn" do%>
           新しいTalk Roomの作成
           <% end %></li>
          
     </ul>
  </div>
</div>

app/views/rooms/new.html.erb
 <div class="box-wrapper">
    <div class="side-bar-room">
    <h2>Talk Room</h2>

           <%= form_with(url: search_rooms_path, local: true, method: :get, class: "search-form") do |form| %>
          <%= form.text_field :keyword, placeholder: "ルーム検索", class: "input-box" %>
          <button class="search-button">
            <%= image_tag "search.png", class:"search-icon" %>
          </button>
        <% end %>

        <ul class="talk-room">
          <% @rooms.each do |room| %>
           <%=link_to room_path(room) do%>
           <p class="talk-room-one"><i class="fas fa-comments">　</i><%= "#{room.name}" %></p>
           <% end %>
          <%end%>
        </ul>
    </div>
    <div class="side-bar-room2">
    <h2>Chat</h2>
        <ul class="side-text-roomenter">
          <li>1対1のチャットはこちらから</li>
           <%=link_to root_path do%>
           <li class="roomenter-btn">トップページへ</li>
           <% end %>
        </ul>
        <ul class="side-login">
          <!--<li><%=link_to("ログインページ","/", class:"side-login-one")%></li>-->
          <li><%=link_to("ログアウト","/users/sign_out",method: :delete,class:"side-login-one" )%></li>
        </ul>
    </div>
 
  <div class="container-new">
    <h2>Talk Roomの作成</h2>
     <ul class="new-text">
          <li> <%= form_with(model:@room, local: true) do |f| %>

      <div class="new-field">
        <%= f.label :ルーム名入力, class:"form-text-new"%><br />
        <%= f.text_field :name, autofocus: true, autocomplete: "nickname",  class:"input-new", placeholder:"10文字以内" %>
      </div>

      <div class="sign-up">
        <%= f.submit "トークルーム作成",class:"make-btn" %>
      </div>
    <% end %></li>
          
     </ul>
  </div>
</div>

app/views/rooms/search.html.erb
  <div class="side-bar-search">
    <h2>Search Result</h2>

        <ul class="talk-room-search">
          <%@talk_room.each do |talk_room|%>
              <%if  @rooms.ids.include?(talk_room.id) %>
                <%=link_to "/rooms/#{talk_room.id}" do%>
                <li class="talk-room-search-one"><i class="fas fa-comments">　</i><%= "#{talk_room.name}" %></li>
              <% end %>
            <% end %>
          <%end%>
        </ul>
    </div>

app/views/rooms/show.html.erb
 <div class="box-wrapper-room">
    <div class="side-bar-room">
    <h2>Talk Room</h2>
           <%= form_with(url: search_rooms_path, local: true, method: :get, class: "search-form") do |form| %>
          <%= form.text_field :keyword, placeholder: "ルーム検索", class: "input-box" %>
          <button class="search-button">
            <%= image_tag "search.png", class:"search-icon" %>
          </button>
        <% end %>

        <ul class="talk-room">
          <% @rooms.each do |room| %>
           <%=link_to room_path(room) do%>
           <p class="talk-room-one"><i class="fas fa-comments">　</i><%= "#{room.name}" %></p>
           <% end %>
          <%end%>
        </ul>

    </div>
    <div class="side-bar-room-calendar">

    <h2>日ごとのチャットを確認</h2>
      <%= month_calendar do |date| %>
        <%= link_to time_show_room_path(@room.id,date),class:"date-one" do %>
          
               <div class="calender-hover"><%= date.day %></div>

        <% end %>
      <% end %>

        <ul class="side-login">
          <li><%=link_to("トップページ","/", class:"side-login-one")%></li>
          <li><%=link_to("ログアウト","/users/sign_out",method: :delete,class:"side-login-one" )%></li>
          <% if @room.user_id == current_user.id %>
          <li><%=link_to("ルームを削除する", room_path,method: :delete,class:"side-login-one", data: {confirm: "このルームを削除しますか？"} )%></li>
          <% end %>
        </ul>
    </div>

    <div class="container-show-room">
    <h2><%="#{@room.name}"%></h2>

        <div id='messages' data-room_id="<%= @room.id %>">
            <% @messages.each do |message|%>
              <%if message.user_id==current_user.id%>
                <div class="mycomment">
                  <p><%=message.content%></p>
                 
                </div>
               <p class="mycomment-time"> <%=message.created_at.month%>/<%=message.created_at.day%>　<%=message.created_at.hour%>:<%= message.created_at.strftime("%M") %></p>
              <%else%>
                <div class="fukidasi">
                  <div class="faceicon">
                  
                    <%= image_tag("user.png", class:"img" )%>
                    <%=message.created_at.month%>/<%=message.created_at.day%>　<%=message.created_at.hour%>:<%= message.created_at.strftime("%M") %>
                  </div>
                 
                  <div class="chatting">
                    <div class="says">
                      <p><%=message.user.nickname%>:<br><%=message.content%></p>
                    </div>
                     
                  </div>
                </div>
              <%end%>
            <%end%>
      </div>

   <div class="room-btn">
   <%= text_field_tag :content, nil, class:"text-box",id:"message",data:{ behavior: 'room_speaker'} %>
     <form id="send-form">
      <input type="submit" value="&#xf1d8;" id="sending" class="far send-box-room">
      <input id="chat_time2" type="hidden" value= "<%=Time.now.hour%>:<%=Time.now.strftime("%M")%>">
    </form>
   </div>
  </div>
</div>

app/views/rooms/time_show.html.erb
 <div class="box-wrapper-room">
    <div class="side-bar-room">
    <h2>Talk Room</h2>
           <%= form_with(url: search_rooms_path, local: true, method: :get, class: "search-form") do |form| %>
          <%= form.text_field :keyword, placeholder: "ルーム検索", class: "input-box" %>
          <button class="search-button">
            <%= image_tag "search.png", class:"search-icon" %>
          </button>
        <% end %>

        <ul class="talk-room">
          <% @rooms.each do |room| %>
           <%=link_to room_path(room) do%>
           <p class="talk-room-one"><i class="fas fa-comments">　</i><%= "#{room.name}" %></p>
           <% end %>
          <%end%>
        </ul>

    </div>
    <div class="side-bar-room-calendar">

    <h2><%=Time.parse(@day_params).year%>年<%=Time.parse(@day_params).month%>月<%=Time.parse(@day_params).day%>日のチャット</h2>
      <%= month_calendar do |date| %>
        <%= link_to time_show_room_path(@room.id,date),class:"date-one" do %>
          <% if Time.parse(@day_params).day == date.day%>
            <div class="calender-one"><%= date.day %></div>
          <% else %>
            <div class="calender-one-hover"><%= date.day %></div>
          <% end %>
        <% end %>
      <% end %>

        <ul class="side-login">
        <li><%=link_to("全ての日を表示",room_path(@room.id), class:"side-login-one")%></li>
          <li><%=link_to("トップページ","/", class:"side-login-one")%></li>
          <li><%=link_to("ログアウト","/users/sign_out",method: :delete,class:"side-login-one" )%></li>
        </ul>
    </div>

    <div class="container-show-room">
    <h2><%="#{@room.name}"%></h2>

        <div id='messages' data-room_id="<%= @room.id %>">
            <% @messages.each do |message|%>

           <% if Time.parse(@day_params).day == message.created_at.day %>
              <%if message.user_id==current_user.id%>
                <div class="mycomment">
                  <p><%=message.content%></p>
                </div>
                 <%=message.created_at.hour%>:<%= message.created_at.strftime("%M") %>
              <%else%>
                <div class="fukidasi">
                  <div class="faceicon">
                    <%= image_tag("user.png", class:"img" )%>
                   <%=message.created_at.hour%>:<%= message.created_at.strftime("%M") %>
                  </div>
                  <div class="chatting">
                    <div class="says">
                      <p><%=message.user.nickname%>:<br><%=message.content%></p>
                    </div>
                  </div>
                </div>
              <%end%>
             <%end%>


            <%end%>
      </div>

  <% if Time.parse(@day_params).day == Time.now.day%>
   <div class="room-btn">
   <%= text_field_tag :content, nil, class:"text-box",id:"message",data:{ behavior: 'room_speaker'} %>
     <form id="send-form">
      <input type="submit" value="&#xf1d8;" id="sending" class="far send-box-room">
    </form>
   </div>
 <%end %>

  </div>
</div>